### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by MatthewJadesphere** [ouoertheo/silero-api-server#17]
Hello I am very dumb please help.

ModuleNotFoundError: No module named 'silero_api_server'

This happens when executing 'run.ps1'

Thank you

**Comment by gab-luz** [comment]
The module location is wrong, try this:
uvicorn silero_api_server.server:app --host 127.0.0.1 --port 8201

**Comment by ouoertheo** [comment]
Thanks so much for reporting! I will get this fixed up.

**Comment by MatthewJadesphere** [comment]
I think the issue was all mine actually. Evidently posting here was all I needed to fix it lol which is why I closed it

**Comment by ouoertheo** [comment]
Bit of column A, bit of column B. I need to fix up the run.ps1 script like gab-luz mentioned after I turned it into a package, so keeping this open as a reminder to myself :D
