### ISSUE TITLE
How to Change Language

### ISSUE THREAD

**Issue by ThesiiNCey** [ouoertheo/silero-api-server#29]
Hey how can change Silero Lang ? its downloading the Default EN files only

**Comment by ouoertheo** [comment]
I was wondering when someone would ask for that feature 😉

That's probably a pretty simple lift. Are you using sillytavern?

**Comment by ThesiiNCey** [comment]
yes i am using Silly tavern

**Comment by Ranger234** [comment]
Hello,

I'm interested in this, too.

**Comment by BahamutRU** [comment]
Is it not implemented? It's a joke?
Basic functionality!
Of course, this is easy to do manually:
1. Choose a model from here https://github.com/snakers4/silero-models/blob/master/models.yml
2. Download it and rename it to model.pt
3. Find model.pt in the root folder of the SillyTavern-extras and replace it with yours.

But why not a flag in the console at startup?..

**Comment by ouoertheo** [comment]
Language selection via API has been released in the latest version v0.3.0
