### ISSUE TITLE
Invalid cross-device link OSError

### ISSUE THREAD

**Issue by MaterialMiko** [ouoertheo/silero-api-server#36]
Using Linux, having installed SillyTavern-Extras "vanilla" with a python virtual environment, and running silero-api-server through SillyTavern-Extras with the following command:
`/path-to-the-python-venv/bin/python /path-to/SillyTavern-Extras/server.py --enable-modules=caption,summarize,classify,silero-tts,chromadb`
with all requirements fulfilled, and the python venv on the same partition as SillyTavern-Extras, results in the following error message before a crash:

- Traceback (most recent call last):
  File "/path-to/SillyTavern-Extras/server.py", line 252, in <module>
    tts_service.generate_samples()
  File /path-to-venv/lib/python3.11/site-packages/silero_api_server/tts.py", line 127, in generate_samples
    os.rename(audio, f"{self.sample_path}/{name}")
OSError: [Errno 18] Invalid cross-device link: 'test.wav' -> '/path-to/SillyTavern-Extras/tts_samples/en_0.wav'

My attempt: replacing "os.rename" with "shutil.move" which failed, returning the error 
"NameError: name 'shutil' is not defined" as I did not import shutil and am not sure how to do so, and if that would fix the issue anyway.

What can I do to fix this issue and make TTS work? Thank you.
Edit: It seems like the issue isn't with silero-api-server but with SillyTavern-Extras: Simply following the silero-api-server recommandations and doing python -m silero_api_server instead of passing through SillyTavernExtras, will work.

**Comment by ouoertheo** [comment]
I had some raw windows pathing in there.  This should be fixed as of version 0.2.9
