### ISSUE TITLE
Please unlock requirements.

### ISSUE THREAD

**Issue by Ph0rk0z** [ouoertheo/silero-api-server#37]
There is no need to push torch 2.0.0.. 2.0.1 works fine. I removed all the reqs versions and nothing changed. Maybe use >= or something.

Cannot expect brand new virtual environment for every single python package. Each of those torch downloads is 2.5gb for cuda. That turns this repo into a multi gig venv or conda instance when it's absolutely unnecessary.

**Comment by ouoertheo** [comment]
Did not realize that implication, thanks for the heads up. Fixed now.
