### ISSUE TITLE
Directory 'samples' does not exist

### ISSUE THREAD

**Issue by Malum327** [ouoertheo/silero-api-server#4]
![Capture](https://user-images.githubusercontent.com/72994011/235341164-fc1a0b9e-2af3-4496-8d82-63ecb6ce6fce.PNG)

**Comment by Fara-on005** [comment]
How did you solve the problem?

**Comment by ouoertheo** [comment]
This is fixed in last update.

**Comment by Fara-on005** [comment]
![image](https://user-images.githubusercontent.com/127478868/235355142-eff27744-a240-4d93-90c3-49a650431f57.png)
I'm not quite sure. After running "run.ps1" it gives an error again

**Comment by ouoertheo** [comment]
Dangit, uploading attempt 2 https://github.com/ouoertheo/silero-api-server/pull/6
![giphy](https://user-images.githubusercontent.com/5422109/235356867-5fbf97f6-08b4-4ae4-b733-872155930488.gif)

**Comment by Malum327** [comment]
All I had to do was create a Samples folder in the root of the project.
