### ISSUE TITLE
Can you create a PiperTTS api server for silly tavern? Please? (suggestion)

### ISSUE THREAD

**Issue by FemBoxbrawl** [ouoertheo/silero-api-server#44]
It would be super awesome, as it is one of if not the fastest generating TTS out there. It works really well for super low end GPU's and when training a voice, it sounds really good!

I do not know how to do this myself, and I do not really have the time to learn how, which is why I am asking.

**Comment by ouoertheo** [comment]
I will not. That's very much a different project.
